version: '3.8'
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=nuvix
      - POSTGRES_PASSWORD=nuvix
      - POSTGRES_DB=nuvix
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5436:5432'

  redisDB:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'